### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by kwiens** [iFixit/pulldasher#7]
- [ ] On new comments that dev_block, un_dev_block, deploy_block, and un_deploy_block: add or remove `deploy_block` and `dev_block` labels to the pull
- [x] If the pull request doesn't have a milestone and the issue does, add the milestone to the pull request
- [x] Watch for [github 'close' keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) as well as [waffle 'connects'](https://github.com/waffleio/waffle.io/wiki/FAQs#prs-closing-keywords) keyword.
  - Ignore the waffle connects issues for now
- [x] Add Issue, issue title, milestone, pull, difficulty scope, and asignee to new metrics table
- [x] Display the difficulty scope in the UI
- [x] Add filters for assigned and milestone.
  - Ex: assigned=soriat,sterlinghirsh,suzukichi,copperwall,anthonypileggi&milestone=8%2F29

cc @davidrans

**Comment by kwiens** [comment]
Difficulty scope me!

**Comment by marczych** [comment]
> On new comments that dev_block, un_dev_block, deploy_block, and un_deploy_block: add or remove deploy_block and dev_block labels to the pull

Any reason to not do the same for "needs CR", "needs QA", and "ready to deploy"? Having a history of when pulls go into different states would be pretty cool. Also, if I sign off on CR, seeing the "needs CR" label be removed and "ready to deploy" be added I can deploy it immediately rather than opening up pulldasher to see if it's in the ready column.

This definitely doesn't have to be lumped in with the dev_block and deploy_block labels, though.

**Comment by marczych** [comment]
It'd be great to see the CR/QA labels at a glance in Waffle too. We'll get this for free once the labels are applied.

**Comment by andyg0808** [comment]
I just threw this feature in with the dev_block and deploy_block labels. It was three more lines of code.

**Comment by kwiens** [comment]
I think we're good! We did everything that didn't require pulldasher modify Github, and I think that's where we want to leave it.
