### ISSUE TITLE
QAing eye: Make visible in non-QA Pulls columns

### ISSUE THREAD

**Issue by addison-grant** [iFixit/pulldasher#94]
This eyeball shows up in the QA Pulls column when someone puts the `QAing` label.
![screen shot 2017-08-17 at 2 28 13 pm](https://user-images.githubusercontent.com/10889879/29434567-55a33db4-8358-11e7-8d3e-c604cfaf9e74.png)

Do
===
Make this eyeball show up in the other columns too!

**Comment by copperwall** [comment]
Not to be a damp towel, but why?

* Whether or not a pull is being QA'd isn't really relevant data to someone doing CR.
* If a pull is in the dev_blocked column, a pull shouldn't be being QA'd.
* If a pull is in the deploy blocked column, it's already been QA'd.
* If a pull is in the CI Blocked column, it's in a special state of limbo where it can technically be CR'd, but shouldn't be QA'd since the first line of test defense failed.

The functionality was originally added so that QA don't step on each other's toes when there's a bunch of pulls in the QA column, since we used to waste a bunch of work when multiple people jumped on an issue at the same time and didn't know it.

**Comment by addison-grant** [comment]
Those are all interesting points, but I have reasons that I like to see where the QAing labels are at any given time. Maybe we can make a toggle that shows the eye on all of them if you want to see it, but by default only show it on the QA Pulls column. The toggle coule be a UI element or a getParam. If we could set a cookie to remember the setting, that'd be nice.

**Comment by lexahall** [comment]
I think it could be nice when looking at the CR column to see if someone is currently QAing the pull. Sometimes it's good to have CR and QA happening at the same time so that the author of the pull can respond to CR comments and QA comments all at once rather than making some code changes to fix CR issues, un_dev_blocking, then having more stuff pointed out by QA, fixing, un_dev_blocking, then more pointed our by CR... etc. 
It's also nice to have the label in the CI column since we often end up QAing things from the CI column when tests are broken, or when we want to get something out quickly and we start QA before tests finish running. 
I can't think of a good reason to have a QAing icon in the ready, deploy_blocked, or dev_blocked columns, since pulls in these places should either already have QA or not be ready for QA.
